version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=esim_user
      - DB_PASSWORD=esim_password
      - DB_NAME=esim_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QPAY_MERCHANT_ID=${QPAY_MERCHANT_ID}
      - QPAY_MERCHANT_PASSWORD=${QPAY_MERCHANT_PASSWORD}
      - QPAY_ENDPOINT=${QPAY_ENDPOINT}
      - ROAMWIFI_API_KEY=${ROAMWIFI_API_KEY}
      - ROAMWIFI_API_URL=http://bpm.roamwifi.com
      - ROAMWIFI_PHONENUMBER=0097688580971
      - ROAMWIFI_PASSWORD=Nogame123roamwifi!
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - esim-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=esim_db
      - POSTGRES_USER=esim_user
      - POSTGRES_PASSWORD=esim_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - esim-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - esim-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - esim-network

volumes:
  postgres_data:
  redis_data:

networks:
  esim-network:
    driver: bridge 